### ISSUE TITLE
KeyError: 'cswSwitchState'

### ISSUE THREAD

**Issue by zxyz** [ziesemer/wershlak-nagios_plugins#3]
Hello,
thanks for updating the plugin. 

For me It works on a Catalyst 6500 two member VSS, but it fails for all stacks I tried. I tested it on Cat2960xr, Cat9300 (IOS-XE), Cat3750X and Cat3850 (IOS). All with the following message:

./check_cisco_stack.py -H test.example.net --snmp-Community [test] -m stack -d
```
2018-06-21 16:14:36,540 - parse_args - *** Debug mode started ***
2018-06-21 16:14:36,540 - parse_args - Printing initial options variables: {'community-file': None, 'auth-key': None, 'community-key': None, 'stack-size': '[2,]', 'mode': 'stack', 'priv-key': None, 'auth-file': None, 'priv-file': None}
2018-06-21 16:14:36,540 - parse_args - Printing initial snmp_kwargs variables: {'DestHost': '[test]', 'Version': 1, 'Community': '[test]'}
2018-06-21 16:14:37,138 - ciscoSnmpWalk - Walking stack table --
2018-06-21 16:14:37,145 - get_stack_info - Member info: ('cswSwitchNumCurrent', '1001', '1', 'UNSIGNED32')
2018-06-21 16:14:37,145 - get_stack_info - Member info: ('cswSwitchNumCurrent', '2001', '2', 'UNSIGNED32')
2018-06-21 16:14:37,145 - ciscoSnmpWalk - Walking stack status --
2018-06-21 16:14:37,151 - get_stack_info - Member info: ('cswSwitchState', '1001', '4', 'INTEGER')
Traceback (most recent call last):
  File "./check_cisco_stack.py", line 681, in main
    result, message = getattr(sys.modules[__name__], "run_{0}".format(options["mode"]))(options)
  File "./check_cisco_stack.py", line 544, in run_stack
    stack = get_stack_info(options)
  File "./check_cisco_stack.py", line 416, in get_stack_info
    member_table[index]["status_num"] = member.val
KeyError: 'cswSwitchState'

```
Interestingly the check_snmp_cisco_stack.pl plugin (version 1.6.6) works for all of them, but the plugin version from @wershlak fails with the same issue.

The icinga2 host is running RHEL 7.4.

Please let me know if I can be of any further help! And thanks for your support!

**Comment by ziesemer** [comment]
Acknowledged.  I haven't even looked into what this could be yet, but am eager to get whatever this is fixed.  If you're willing to work on this with me further as you have access to stacks where this is currently happening, that would be perfect.

**Comment by zxyz** [comment]
Great! Let me know what you need! Thanks!

**Comment by ziesemer** [comment]
Are you running Cisco IOS 15.0(2.0.11), or a similar version prior to 15.2(6.0.50a)E2 ?

I'm betting this is due to a Cisco bug:  https://quickview.cloudapps.cisco.com/quickview/bug/CSCvj16030

If you believe otherwise, can you please provide the output of an `snmpwalk`, including `1.3.6.1.4.1.9.9.500.1.2.1.1.6 -On`, as per the Cisco bug reference?

**Comment by zxyz** [comment]
I'm on site on Monday, then I can provide the snmpwalks. 

The OS versions used are:

IOS 16.3.5.b, IOS 15.0(2a)EX5, IOS-XE 16.6.2 and IOS 15.0(2)SE9

so probably (not only) the cisco bug due to IOS-XE and IOS 16.X beeing affected.

**Comment by ziesemer** [comment]
@zxyz - Thanks.  When you do, please also provide an output for `1.3.6.1.4.1.9.9.500.1.2.1.1.6 -On` as well.

**Comment by ziesemer** [comment]
@zxyz - Upon further review - and getting a lab environment back up-and-running to look at this - I think there is more going on here, and most likely unrelated to any concerns with the versions or data being returned by your Cisco devices.

Across my testing on Ubuntu 18.04, CentOS 7.5.1804, and Cygwin - my `Member info` debug outputs are quite different than yours.  For example (timestamps omitted):

```
ciscoSnmpWalk - Walking stack table --
get_stack_info - Member info: ('enterprises.9.9.500.1.2.1.1.1.1001', '', '1', 'GAUGE')
get_stack_info - Member info: ('enterprises.9.9.500.1.2.1.1.1.2001', '', '2', 'GAUGE')
ciscoSnmpWalk - Walking stack status --
get_stack_info - Member info: ('enterprises.9.9.500.1.2.1.1.6.1001', '', '4', 'INTEGER')
get_stack_info - Member info: ('enterprises.9.9.500.1.2.1.1.6.2001', '', '4', 'INTEGER')
get_stack_info - Stack info table to return: {'2001': {'status': 'ready', 'index': '2001', 'number': '2', 'status_num': '4'}, '1001': {'status': 'ready', 'index': '1001', 'number': '1', 'status_num': '4'}}
```

Observations:
* The numeric OID suffices are included in the 1st positions / tags.
   * Yours are named (only) `cswSwitchNumCurrent`.
* The 2nd positions / iids are all empty.
   * Yours include what the script is otherwise expecting to be the ending suffix on the tag.
* The 4th positions / data types are all gauge / integer, respectively.
   * Yours begin with `UNSIGNED32`.

Reference: https://sourceforge.net/p/net-snmp/code/ci/master/tree/python/README

Ultimately, the current script is extracting the `1001`, `2001` from the stack table, then expecting to see matching entries in the stack statuses.  In your case, `cswSwitchNumCurrent` is the only value pulled from the stack table (and overwriting a single entry) - and then `cswSwitchState` is never found when it next looks for the stack statuses.

## Why is this happening?

I'm not exactly sure - but am guessing there are some additional MIBs and/or other netsmp preferences on your system.  (You probably have completed other SNMP-related efforts here, as part of a larger monitoring roll-out?)  I'm thinking that some additional MIBs are loaded, and are effectively changing the interpretation of the received results - by netsnmp before they are received back to the script.

Any of the following that you could provide could prove useful here, for either the immediate resolution and/or for future reference:
* Along the lines of http://net-snmp.sourceforge.net/wiki/index.php/TUT:Using_and_loading_MIBS , please provide the output of `net-snmp-config --default-mibdirs` - and if possible, a listing of the files in each included directory.
* Likewise, I'd be interested in any relevant settings included in any `snmp.conf` or `snmp.local.conf` files - either under `/etc/snmp/` or `$HOME/.snmp/` (as per `man snmp.conf`).
* `snmpwalk` outputs for `1.3.6.1.4.1.9.9.500` - both with and without `-On` included as an argument at the beginning of the command (unlike as listed above and referenced in the Cisco bug report).

I can nearly replicate your current outputs by passing `--snmp-UseNumeric=1` to the script on my side, then receiving the following debug output:

```
ciscoSnmpWalk - Walking stack table --
get_stack_info - Member info: ('.1.3.6.1.4.1.9.9.500.1.2.1.1.1', '1001', '1', 'GAUGE')
get_stack_info - Member info: ('.1.3.6.1.4.1.9.9.500.1.2.1.1.1', '2001', '2', 'GAUGE')
ciscoSnmpWalk - Walking stack status --
get_stack_info - Member info: ('.1.3.6.1.4.1.9.9.500.1.2.1.1.6', '1001', '4', 'INTEGER')
```

... with an identical traceback, but with `KeyError: '6'`.

I'm thinking I should unconditionally set the `UseNumeric=1` option, and then update the script to make use of the returned `iid` fields - which would also eliminate the need to split off the last suffix off of the returned tags (1st positions).  I'll work on putting a revised script together with this approach - but would still like to understand the differences we are seeing here.

**Comment by zxyz** [comment]
I think you got it!

I added lots of MIBS on the system from the **LibreNMS** project [1]. They do a really good job in maintaining them. I stored them under `/opt/mibs` and added only the ones in the "root" directory plus the cisco ones. So my `/etc/snmp/snmp.conf` file looks as follows:
```

mibdirs +/opt/mibs:/opt/mibs/cisco
mibs +ALL
```

the requested nmp walks look as follows (excerpts):

```
CISCO-STACKWISE-MIB::cswMaxSwitchNum.0 = Gauge32: 9
CISCO-STACKWISE-MIB::cswMaxSwitchConfigPriority.0 = Gauge32: 15
CISCO-STACKWISE-MIB::cswRingRedundant.0 = INTEGER: true(1)
CISCO-STACKWISE-MIB::cswEnableStackNotifications.0 = INTEGER: true(1)
CISCO-STACKWISE-MIB::cswEnableIndividualStackNotifications.0 = BITS: FF FF FE 00 stackPortChange(0) stackNewMaster(1) stackMismatch(2) stackRingRedundant(3) stackNewMember(4) stackMemberRemoved(5) stackPowerLinkStatusChanged(6) stackPowerPortOperStatusChanged(7) stackPowerVersionMismatch(8) stackPowerInvalidTopology(9) stackPowerBudgetWarning(10) stackPowerInvalidInputCurrent(11) stackPowerInvalidOutputCurrent(12) stackPowerUnderBudget(13) stackPowerUnbalancedPowerSupplies(14) stackPowerInsufficientPower(15) stackPowerPriorityConflict(16) stackPowerUnderVoltage(17) stackPowerGLS(18) stackPowerILS(19) stackPowerSRLS(20) stackPowerSSLS(21) stackMemberToBeReloadedForUpgrade(22)
CISCO-STACKWISE-MIB::cswStackDomainNum.0 = Gauge32: 0
CISCO-STACKWISE-MIB::cswStackType.0 = Gauge32: 0
CISCO-STACKWISE-MIB::cswStackBandWidth.0 = Gauge32: 0
```

vs:

```
.1.3.6.1.4.1.9.9.500.1.1.1.0 = Gauge32: 9
.1.3.6.1.4.1.9.9.500.1.1.2.0 = Gauge32: 15
.1.3.6.1.4.1.9.9.500.1.1.3.0 = INTEGER: true(1)
.1.3.6.1.4.1.9.9.500.1.1.4.0 = INTEGER: true(1)
.1.3.6.1.4.1.9.9.500.1.1.5.0 = BITS: FF FF FE 00 stackPortChange(0) stackNewMaster(1) stackMismatch(2) stackRingRedundant(3) stackNewMember(4) stackMemberRemoved(5) stackPowerLinkStatusChanged(6) stackPowerPortOperStatusChanged(7) stackPowerVersionMismatch(8) stackPowerInvalidTopology(9) stackPowerBudgetWarning(10) stackPowerInvalidInputCurrent(11) stackPowerInvalidOutputCurrent(12) stackPowerUnderBudget(13) stackPowerUnbalancedPowerSupplies(14) stackPowerInsufficientPower(15) stackPowerPriorityConflict(16) stackPowerUnderVoltage(17) stackPowerGLS(18) stackPowerILS(19) stackPowerSRLS(20) stackPowerSSLS(21) stackMemberToBeReloadedForUpgrade(22)
.1.3.6.1.4.1.9.9.500.1.1.6.0 = Gauge32: 0
.1.3.6.1.4.1.9.9.500.1.1.7.0 = Gauge32: 0
.1.3.6.1.4.1.9.9.500.1.1.8.0 = Gauge32: 0
```

So I think it's a very good idea to always work with the numeric numers to make the script independent from the MIBS installed on the individual system.

Thanks a lot! Great work!

[1] https://github.com/librenms/librenms/tree/master/mibs

**Comment by ziesemer** [comment]
@zxyz - To update this, I need to ensure we don't then break the processing being used for VSS mode.  Would you be able to help me with getting some snmpwalks from your Catalyst 6500 two member VSS?  I'd be looking for `-On` exports for the following OID roots:

* `.1.3.6.1.4.1.9.9.388.1.1.4.0` (`cvsSwitchMode`)
* `.1.3.6.1.4.1.9.9.388.1.1.5.0` (`cvsSwitchConvertingStatus`)
* `.1.3.6.1.4.1.9.9.388.1.3.1.1` (`cvsVSLConnectionEntry`)
* `.1.3.6.1.4.1.9.9.388.1.2.2.1` (`cvsChassisEntry`)

**Comment by zxyz** [comment]
@ziesemer here we go, the requested snmpwalk OIDs of the 2 member VSS:

```
.1.3.6.1.4.1.9.9.388.1.1.4.0 = INTEGER: 2
.1.3.6.1.4.1.9.9.388.1.1.5.0 = INTEGER: 2
.1.3.6.1.4.1.9.9.388.1.3.1.1.2.255 = Gauge32: 2
.1.3.6.1.4.1.9.9.388.1.3.1.1.2.256 = Gauge32: 1
.1.3.6.1.4.1.9.9.388.1.3.1.1.3.255 = INTEGER: 1
.1.3.6.1.4.1.9.9.388.1.3.1.1.3.256 = INTEGER: 1
.1.3.6.1.4.1.9.9.388.1.3.1.1.4.255 = Hex-STRING: 07 E2 06 04 08 1F 3C 00
.1.3.6.1.4.1.9.9.388.1.3.1.1.4.256 = Hex-STRING: 07 E2 06 04 08 1F 3C 00
.1.3.6.1.4.1.9.9.388.1.3.1.1.5.255 = Gauge32: 2
.1.3.6.1.4.1.9.9.388.1.3.1.1.5.256 = Gauge32: 2
.1.3.6.1.4.1.9.9.388.1.3.1.1.6.255 = Gauge32: 2
.1.3.6.1.4.1.9.9.388.1.3.1.1.6.256 = Gauge32: 2
.1.3.6.1.4.1.9.9.388.1.3.1.1.7.255 = INTEGER: 1
.1.3.6.1.4.1.9.9.388.1.3.1.1.7.256 = INTEGER: 1
.1.3.6.1.4.1.9.9.388.1.2.2.1.1.2 = Gauge32: 1
.1.3.6.1.4.1.9.9.388.1.2.2.1.1.8000 = Gauge32: 2
.1.3.6.1.4.1.9.9.388.1.2.2.1.2.2 = INTEGER: 2
.1.3.6.1.4.1.9.9.388.1.2.2.1.2.8000 = INTEGER: 3
.1.3.6.1.4.1.9.9.388.1.2.2.1.3.2 = Timeticks: (190240959) 22 days, 0:26:49.59
.1.3.6.1.4.1.9.9.388.1.2.2.1.3.8000 = Timeticks: (190240959) 22 days, 0:26:49.59
```

TNX!

**Comment by ziesemer** [comment]
@zxyz - I believe this is fixed.  Would you please validate with 6ef5680?  Once confirmed, I will tag this as a 1.7 release.  Thank you for the report, as well as the snmpwalk's - they were invaluable here.

**Comment by zxyz** [comment]
@ziesemer thanks a lot! I'll be able to check on monday and will get back to you asap.
Thanks again for the great response!

**Comment by zxyz** [comment]
hey @ziesemer, I can confirm that the plugin now works for all of my VSS and stacks! 
Thanks a lot!
